### ISSUE TITLE
Advanced Filter (Filter date time type)

### ISSUE THREAD

**Issue by sheldonyss** [Microsoft/powerbi-models#14]
I tried to filter my report by creating a Date filter but Power BI service always return this error: 
undefined:1 Uncaught (in promise) Object {message: "Invalid filter definition"}

Below is the TypeScript code of filter.
static predefinedFilter2 = new pbi.models.AdvancedFilter({ table: "f_msANA_byRelease_transformed", column: "aaValuePeriodStartTime" }, "And", { operator: "GreaterThan", value: "1 June 2016" } // , // { // operator: "None", // value: "2016-06-05 23:59:59" // } );

I also tried "2016-06-05T23:59:59Z" format but received the same error message.

Can anyone provide an example of filter report by date?

**Comment by pkwiecien** [comment]
Example of expected date format is 2014-06-01T00:00:00.000Z
You can try it out using our filters demo that is based on Retail Analysis Sample from Power BI: https://microsoft.github.io/PowerBI-JavaScript/demo/filters.html   
Specify the following parameters:
Table: Time, Column: Date, Operatory type: Advanced, Logical Operator: And, Value: 2014-06-01T00:00:00.000Z, Condition: GreaterThan

**Comment by mattmazzola** [comment]
I added this to the README.md in this commit:
https://github.com/Microsoft/powerbi-models/commit/a4d98cb81309eff7b63d117346015d6ef430cd59
