### ISSUE TITLE
Dependency JSEN requires unsafe-eval

### ISSUE THREAD

**Issue by vangorra** [Microsoft/powerbi-models#48]
Unsafe-eval is discouraged when using Content-Security-Policy (CSP) best practices. The JSEN dependency uses these features (eval, new Function). Doing so prevents powerbi-models from properly functioning. Allowing the use of these functions opens then app up for potential XSS attacks.

Of all the dependencies we use for our app, powerbi-models is the only one that has any use for these functions.

Can we use a different module for json schema validation?

**Comment by ali-hamud** [comment]
hi @vangorra 
Do you know if there is another library like jsen which is CSP compatible?

**Comment by vangorra** [comment]
I checked out a few projects by searching their bundled js files for eval, new Function, Function.apply, Function.apply. These are the projects I'm rather certain are CSP safe, sorted by number of github stars.

- ajv - Using ajv-cli, generates JS code at build time to avoid unsafe-eval and speed up validation.
- tv4
- jayschema
- jsonschema

**Comment by ali-hamud** [comment]
@vangorra 
Hi,
problem should be solved by now as we removed dependency on jsen library.
please check.
