### ISSUE TITLE
Unable to resolve - This filter can't be applied because the corresponding field is invalid

### ISSUE THREAD

**Issue by chetan2309** [Microsoft/powerbi-models#50]
Hi,

I downloaded the MVC application and made necessary changes to the code to pull in reports from my account. Everything worked. Perfectly.

However, now I am applying filters through button interaction and it is not working. The same code is able to apply filters on the default report that we get from powerbi. I mean to say if I upload that report to my account the code works well to apply filters and report gets filtered.

Below is the output of the filter object that is created by the code. I am using PowerBI js 2.3.0

```
[]({$schema: "http://powerbi.com/product/schema#basic", target: {…}, operator: "In", values: Array(1)}
$schema
:
"http://powerbi.com/product/schema#basic"
operator
:
"In"
target
:
column
:
"CROP_YEAR"
table
:
"Agrimine Vended"
__proto__
:
Object
values
:
Array(1)
0
:
"2014"
length
:
1
__proto__
:
Array(0)
__proto__
:
Object)
```
<img width="282" alt="bug_powerbi" src="https://user-images.githubusercontent.com/539289/27680440-576799d8-5cd9-11e7-9d40-7bd0eb72afdc.PNG">

If I apply a  report level from PowerBI it works correctly. So I am unable to debug what exactly is wrong. I am attaching here a screen shot to of powerbi tables to verify if I am putting right table names and column names. From the SS I concluded that the table name is "Agrimine Vended" and column name is "CROP_YEAR". I didn't create this report however received a pbix file.

I am pretty new to powerbi ecosystem. Any help will be appreciated.

Best,
Chetan

**Comment by ali-hamud** [comment]
The best way to code pre-defined filters is:
1) Apply a filter in the service and save the report.
2) Embed the report.
3) Call GetFilters => this will give you a json of the filter.
4) Copy it to the code and call setFilters with it.

hope this helps.

for code samples you can use the live sample:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html

**Comment by chetan2309** [comment]
Thanks @ali-hamud this helped. The problem that I was passing year as string.

I think the error messages were not clear to help me figure out this. Can we improve error messages to be more specific from power bi?

Best,
Chetan

**Comment by chetan2309** [comment]
The problem was not with code. I was passing wrong type. String instead of Number. I think it was because the error message was generic and could not tell exact error.
