### ISSUE TITLE
How to Construct a Date filter in Embedded PowerBI Report

### ISSUE THREAD

**Issue by dead8171** [Microsoft/powerbi-models#54]
Can someone explain to me how can I create a date filter inside the Embedded report, using javascript, How should be date formatted as if I want to setup the date filter inside the java script code??

Do I need to edit the PowerBi column to set the date filter or I can manually use it, Please throw some light on this as I am confused how to use.

**Comment by ali-hamud** [comment]
The format of the filters are detailed in this page:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters

Date format should be as defined in your model.

If you find it hard to create a filter, the easiest way is:
1) Embed a report.
2) Create filters manually by selecting filter values in filter pane.
3) call report.getFilters() method. getFilters gives you a list of filters which you can use to apply the filters back on the report.
