### ISSUE TITLE
Cant Embed my PowerBI report Getting Errors while doing this

### ISSUE THREAD

**Issue by dead8171** [Microsoft/powerbi-models#56]
Getting following errors while embeding my powerbi report and the report is not getting loading up.

`powerbi.js:555 Uncaught [{…}]0: message: "tokenType must be a number"__proto__: Objectlength: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object`
Embed.load @ powerbi.js:555
(anonymous) @ powerbi.js:769

**Comment by ali-hamud** [comment]
Token type must be a number: 0 or 1.
You can use the enum defined in powerbi-models for that, which is:
models.TokenType.Embed or models.TokenType.Aad
please follow the example in the live demo:

aka.ms/pbijs
